Homework 6
xo4yxypmy/CPP_for_GameDev_r_d pull request #6
Opened 2023-11-24 20:58 UTC by xo4yxypmy

Check my homework pls

2023-11-25 10:31 UTC, bohdanpc requested changes

2023-11-25 10:31 UTC, bohdanpc commented on homework6/homework6.cpp
> +    std::cout << "Element number " << nF << " in the Fibonacci sequence: " << (nF > 2 ? f2 : 1) << std::endl;
f2 is initialized with 1 anyway, so this check is redundant.

2023-11-25 10:31 UTC, bohdanpc commented on homework6/homework6.cpp
> +            std::cout << (b % 2);
the correct pattern is different. 
your output will always start with the same digit on each row

2023-11-25 12:25 UTC, xo4yxypmy commented on homework6/homework6.cpp
> +    std::cout << "Element number " << nF << " in the Fibonacci sequence: " << f2 << std::endl;
changed

2023-11-25 12:29 UTC, xo4yxypmy commented on homework6/homework6.cpp
> +            std::cout << (a + b + 1) % 2;
changed: now the loop has the same pattern as in the task

2023-11-29 16:25 UTC, helen-black approved these changes

2023-11-29 16:25 UTC, merged